version: "3.8"

services:
  beaver_db:
    image: postgres:latest
    container_name: beaver_api_db
    restart: unless-stopped
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "1"
          memory: 1000M
    environment:
      POSTGRES_USER: beaver_api
      POSTGRES_PASSWORD: beaver_api
      POSTGRES_DB: beaver_api
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U beaver_api -d beaver_api"]
      interval: 5s
      timeout: 5s
      retries: 10
